= 20180625 周 ARTS

== Algorithm

=== 1. Two Sum

Given an array of integers, return indices of the two numbers such that they add up to a specific target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

https://leetcode.com/problems/two-sum/description/[Two Sum - LeetCode]

[source,java]
----
include::{source_base_path}/TwoSum.java[]
----


=== 7. Reverse Integer

Given a 32-bit signed integer, reverse digits of an integer.

https://leetcode.com/problems/reverse-integer/description/[Reverse Integer - LeetCode]

[source,java]
----
package com.diguage.algorithm.leetcode;

import java.util.ArrayList;
import java.util.List;

/**
 * = 7. Reverse Integer
 *
 * https://leetcode.com/problems/reverse-integer/description/[Reverse Integer - LeetCode]
 *
 * Given a 32-bit signed integer, reverse digits of an integer.
 *
 * .Example 1:
 * [source]
 * ----
 * Input: 123
 * Output: 321
 * ----
 *
 * .Example 2:
 * [source]
 * ----
 * Input: -123
 * Output: -321
 * ----
 *
 * .Example 3:
 * [source]
 * ----
 * Input: 120
 * Output: 21
 * ----
 *
 * == Note
 *
 * Assume we are dealing with an environment which could only store integers within the 32-bit signed integer range: [−231,  231 − 1]. For the purpose of this problem, assume that your function returns 0 when the reversed integer overflows.
 *
 * @author D瓜哥, https://www.diguage.com/
 * @since 2018-07-01
 */
public class ReverseInteger {
    public static int reverse(int x) {
        if (x == 0
                || x > Math.pow(2, 31)
                || x < -Math.pow(2, 31)) {
            return 0;
        }

        int sign = 1;
        int positiveNum = x;
        if (x < 0) {
            sign = -1;
            positiveNum = x * sign;
        }

        boolean zeroOfEnd = true;
        List<Integer> bitNums = new ArrayList<>(25);
        for (int i = positiveNum; i > 0; ) {
            int bitNum = i % 10;
            i = i / 10;
            if (zeroOfEnd && bitNum == 0) {
                continue;
            }
            bitNums.add(bitNum);
            if (zeroOfEnd) {
                zeroOfEnd = false;
            }
        }

        long result = 0;
        for (int j = 0; j < bitNums.size(); j++) {
            result += bitNums.get(j) * ((long) Math.pow(10, bitNums.size() - j - 1));
        }
        if (result > Integer.MAX_VALUE) {
            return 0;
        }

        return (int) result * sign;
    }

    public static void main(String[] args) {
        System.out.println(reverse(120));
        System.out.println(reverse(123));
        System.out.println(reverse(-123));
        System.out.println(reverse(-10305));
        int i = 1534236469;
        System.out.println(reverse(i));
        System.out.println(Integer.bitCount(i));
        System.out.println(i);
        System.out.println(Integer.MAX_VALUE);
        System.out.println(Integer.MIN_VALUE);
    }
}
----

这道题费了些周折。提交代码后，在1000多个测试用例处报错了，入参是： `1534236469`。返回结果是一个很奇怪的数字。后来，终于意识到 `1534236469` 不越界，但是翻转过来，`9646324351` 是越界的。把中间技术结果用 `long` 表示后，就OK了。

=== 9. Palindrome Number

Determine whether an integer is a palindrome. An integer is a palindrome when it reads the same backward as forward.

https://leetcode.com/problems/palindrome-number/description/[Palindrome Number - LeetCode]

[source,java]
----
package com.diguage.algorithm.leetcode;

import java.util.ArrayList;
import java.util.List;

/**
 * = 9. Palindrome Number
 *
 * https://leetcode.com/problems/palindrome-number/description/[Palindrome Number - LeetCode]
 *
 * Determine whether an integer is a palindrome. An integer is a palindrome when it reads the same backward as forward.
 *
 * .Example 1:
 * [source]
 * ----
 * Input: 121
 * Output: true
 * ----
 *
 * .Example 2:
 * [source]
 * ----
 * Input: -121
 * Output: false
 * Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.
 * ----
 *
 * .Example 3:
 * [source]
 * ----
 * Input: 10
 * Output: false
 * Explanation: Reads 01 from right to left. Therefore it is not a palindrome.
 * ----
 *
 * == Follow up
 *
 * Coud you solve it without converting the integer to a string?
 *
 * @author D瓜哥, https://www.diguage.com/
 * @since 2018-07-01
 */
public class PalindromeNumber {
    public static boolean isPalindrome(int x) {
        boolean result = true;
        if (x < 0) {
            return false;
        }
        int multiBitNumStarter = 10;
        if (x < multiBitNumStarter) {
            return result;
        }
        List<Integer> bitNums = new ArrayList<>(25);
        for (int i = x; i > 0; i /= 10) {
            bitNums.add(i % 10);
        }
        int halfLength = bitNums.size() / 2;
        for (int i = 0; i < halfLength; i++) {
            if (!bitNums.get(i).equals(bitNums.get(bitNums.size() - i - 1))) {
                result = false;
                break;
            }
        }

        return result;
    }

    public static void main(String[] args) {
        System.out.println(isPalindrome(121));
        System.out.println(isPalindrome(-121));
        System.out.println(isPalindrome(10));
    }
}
----

这道题一次通过，爽…

如果想省事，可以把数字当字符串处理，来一个 `java.lang.StringBuilder#reverse()` 就OK了。

== Review

看了一些，重点介绍两篇文章：

https://medium.com/@IbrahimOKareem/a-beginners-guide-to-the-last-10-years-of-the-internet-b1f7841c4512[A beginner’s guide to the last 10 years of the internet]

回顾了互联网十多年的发展历程，并且从上网人数、网页设计、网速、浏览器、社交网络、移动时代、视频流等几个方面着重对比了前后十年的不同之处。并预言语音搜索、社会商业、移动网络、人工智能等方面将是接下来的发展重点。

https://medium.com/@Amitch5903/top-10-chinese-startups-to-watch-in-2018-90690d7d6109[Top 10 Chinese Startups to Watch in 2018 – Alex Mitchell – Medium]

作者先从背景入手，介绍了中国创业公司面临的几个机遇与问题：人工智能爆发、政府干预、法律缺失、技术的使用模式创新、人口众多等。然后简要分析了十家优质的创业公司，其中包括有：

. http://www.cloudwalk.cn/[云从科技]
. https://www.souche.com/[大搜车]
. http://www.imlaidian.com/[来电科技]
. https://www.tujia.com/[途家网]
. https://t.vipkid.com.cn/[VIPKID]
. https://www.icarbonx.com/[iCarbonX]
. http://www.deepglint.com/[格灵深瞳]
. https://www.liulishuo.com/[流利说]
. https://www.pico-interactive.com/neo[Pico Interactive]
. http://www.roobo.com/[ROOBO]

不过，感觉作者对中国的了解有些偏差，个人感觉“途家网”已解决不能算是创业公司了。

== Tip

这周闲暇时间都在看《重构》，分享几个重构技巧吧：

. Extract Method
. Introduce Explaining Variable
. Replace Method with Object
. Move Method
. Move Field

== Share

=== 读《重构》的感想

最近在看《重构》，说一下自己的感受。

在几年前看《大话设计模式》时，被设计模式的精巧之处及对面向对象特性恰到使用所深深折服，产生的直接影响就是加深了对面向对象的理解和使用。

现在看《重构》，起初代码不甚优雅，但是在通过反复使用作者介绍的简单朴实的重构技术，经过多次加工优化，代码逐渐清晰明了。尤其是，现在看的“Chapter 7 Moving Features Between Objects”，通过对代码重构，可以使代码越来越“面向对象化”。

如果说设计模式可以让我们在设计的时候，高屋建瓴地做出一个面向对象的设计；那么，个人认为，重构技术为已有代码修了一条慢慢通向面向对象的康庄大道，可以让我们一步一步把代码优化出面向对象的味道来。

=== 参加团建的收获

周六（2018年06月30日），参加公司组织的团建。中间一个环节，分组比赛完成任务。说一下自己的收获吧。

. *任务分解* 一共有16个任务，我们组五个人，分解到每个人，只需要关注自己负责的三个任务即可，这样降低了大家的记忆负担，任务明确，无形中提高了效率。
. *对手也许也是朋友* 由于很多任务需要超过五个人才能完成，我们刚开始找游客协助。后来，**开阔思路，对手也是游客，不能仅仅关注竞争，也许还可以合作**，实现互利共生，尽可能多地完成任务。
. *方法总比困难多* 其中一个任务需要口红。整个团队里，只有三个女生。外出团建，根本没有带口红。我们直接在途中，寻找了一些红色的小野果，捏碎当燃料了。
. *有压力，更有动力* 总共有 2 个小时来完成任务。我们在剩下最后 40 分钟的时候，才刚刚走了去程的三分之二，最多四分之三。然后就加快进度，到底终点，完成任务时，只剩下半个小时多点时间，然后我们就一路狂奔向回赶，跑回到始发位置，我们还剩下10分钟，又紧锣密鼓地完成了最后两个任务。
. *要想走得远，大家一起走* 非常感谢同一个队的小伙伴，尤其那个小女生，在一路狂奔向回跑的过程中，小女生一直坚持下来，没有掉队，非常难得。任务中，也需要各个小伙伴协作，大家集思广益，共同想办法，克服困难，完成了所有任务，拿到满分的成绩！为每个小伙伴鼓掌。

== English

现在每天背诵五句“新概念英语2”的语句，复习大概 40 句。已经坚持 59 天。

接下来，准备每天对一篇文章，把生词也背一下。